SELECT Group_Name, COLLECTOR_CODE, Incentive
FROM (
    SELECT *,
           RANK() OVER(PARTITION BY Group_Name ORDER BY Incentive DESC) as rnk
    FROM (SELECT 
    COLLECTOR_CODE, OUTSTANDING_BALANCE, JUDGE_TYPE, Group_Name, AGE_OF_WRITE_OFF, AUTO_TYPE_NAME,
    CASE 
        WHEN AUTO_TYPE_NAME = 'Motorcycle' THEN
            CASE 
                WHEN AGE_OF_WRITE_OFF <= 1 THEN
                    CASE WHEN OUTSTANDING_BALANCE < 10000 THEN 1500 WHEN OUTSTANDING_BALANCE < 30000 THEN 2000 ELSE 2500 END
                WHEN AGE_OF_WRITE_OFF > 1 AND AGE_OF_WRITE_OFF <= 3 THEN
                    CASE WHEN OUTSTANDING_BALANCE < 10000 THEN 2000 WHEN OUTSTANDING_BALANCE < 30000 THEN 2500 ELSE 3000 END
            END
        WHEN AUTO_TYPE_NAME = 'Non Motorcycle' THEN
            CASE 
                WHEN AGE_OF_WRITE_OFF <= 1 THEN
                    CASE WHEN OUTSTANDING_BALANCE < 100000 THEN 2500 WHEN OUTSTANDING_BALANCE < 300000 THEN 3100 ELSE 3600 END
                WHEN AGE_OF_WRITE_OFF > 1 AND AGE_OF_WRITE_OFF <= 3 THEN
                    CASE WHEN OUTSTANDING_BALANCE < 100000 THEN 3000 WHEN OUTSTANDING_BALANCE < 300000 THEN 3600 ELSE 4100 END
            END
    END AS Incentive
FROM (
   SELECT
    w.AGREEMENT_NO,
    w.COLLECTOR_CODE,
    w.OUTSTANDING_BALANCE, 
    j.JUDGE_TYPE,
    CASE 
        WHEN w.OUTSTANDING_BALANCE < 50000 THEN 'กลุ่มที่ 1'
        WHEN w.OUTSTANDING_BALANCE >= 50000 AND (j.JUDGE_TYPE NOT IN (1, 2) OR j.JUDGE_TYPE IS NULL) THEN 'กลุ่มที่ 2'
        WHEN w.OUTSTANDING_BALANCE >= 50000 AND j.JUDGE_TYPE IN (1, 2) THEN 'กลุ่มที่ 3'
    END AS Group_Name,
    w.AGE_OF_WRITE_OFF,
    w.AUTO_TYPE_NAME
FROM TB_DATA_WO w
LEFT JOIN TB_DATA_JUDETYPE j ON w.AGREEMENT_NO = j.AGREEMENT_NO
WHERE NOT EXISTS (
    SELECT 1 FROM TB_CAR_CASE c 
    WHERE c.AGREEMENT_NO = w.AGREEMENT_NO
)
) Sub )
) t
WHERE rnk = 1;